import { APP_NAME, APP_REPO_URL } from '../../shared/constants'

// Attribution footer appended to the GitHub review body at submission time.
//
// This is injected programmatically — NOT generated by Codex and NOT stored on
// the draft — so it never appears in the editor or the markdown live preview;
// it only rides along on the body sent to GitHub. Plain markdown (an <hr> plus
// an italic link) so GitHub renders it without relying on inline HTML.
const FOOTER_SEPARATOR = '\n\n---\n'
const FOOTER_LINE = `*🔀 AI-assisted review by [${APP_NAME}](${APP_REPO_URL})*`
const FOOTER_BLOCK = `${FOOTER_SEPARATOR}${FOOTER_LINE}`

/**
 * Returns the review markdown with the attribution footer appended. Idempotent:
 * if THIS exact footer is already the body's tail it's returned unchanged so we
 * never double-stamp. The guard matches the footer block at the end — NOT any
 * mention of the repo URL, since a reviewer may legitimately link to the repo
 * (or a /issues, /releases path) in the review prose and must still get stamped.
 */
export function withReviewBranding(markdown: string): string {
  const trimmed = markdown.trimEnd()
  if (trimmed.endsWith(FOOTER_BLOCK)) return `${trimmed}\n`
  return `${trimmed}${FOOTER_BLOCK}\n`
}
