import { APP_NAME, APP_REPO_URL } from '../../shared/constants'

// Attribution footer appended to the GitHub review body at submission time.
//
// This is injected programmatically — NOT generated by Codex and NOT stored on
// the draft — so it never appears in the editor or the markdown live preview;
// it only rides along on the body sent to GitHub. Plain markdown (an <hr> plus
// an italic link) so GitHub renders it without relying on inline HTML.
const FOOTER_SEPARATOR = '\n\n---\n'
const FOOTER_LINE = `*🔀 AI-assisted review by [${APP_NAME}](${APP_REPO_URL})*`

/**
 * Returns the review markdown with the attribution footer appended. Idempotent:
 * if the body already carries the attribution (defensive — drafts never do),
 * it's returned unchanged so we never double-stamp.
 */
export function withReviewBranding(markdown: string): string {
  if (markdown.includes(APP_REPO_URL)) return markdown
  return `${markdown.trimEnd()}${FOOTER_SEPARATOR}${FOOTER_LINE}\n`
}
